import numpy
screen = [[0]*120]*40
screen = numpy.array(screen)
objbrick = []
#component = [[]*120]*40
paddle = "^^^^^^"
brick1 = "▭"
ball = "◦"
exppaddle = "@"
shrpaddle = "*"
fastball = "&"
thruball = "%"
paddlegrab = "$"
ballmultiply = "#"
bullet = "."
shoot1 = "!"
bomb= "+"
ufo ="(__)"
objballmultiply = []
objpaddle = []
objball = []
objexppaddle = []
objshrpaddle = []
objthruball = []
objfastball = []
objpaddlegrab = []
objshoot = []
objbullet = []
objboss = []
objbombs = []
flag = 0
lives = 10
timelimit = 20
relball = 0
newlife = 0
health = 10
# yinc = -1
score  = 0 
time = 0
paddlelength = 6
level = 1
timelimitlvl = 25
tilvl = 0
tatlvl = 0
decrease = 0
shoot = 0
timepowerup = 0
